---
#### Metadata
title: Title
short: Short title for headings
journal: "AER" # AER, AEJ, PP, JEL
month: 
year: 
vol: 
issue: 
jel: 
keywords: 
issueName: 
author: 
  - name: author1
    firstname: name1
    surname: surname1
    email: email1
    affiliation: institution1
  - name: author2
    firstname: name2
    surname: surname2
    email: email2
    affiliation: institution2
abstract: |
  `r paste(readLines("_abstract.Rmd"), collapse = '\n  ')`
acknowledgements:
draft: true # set formatting to draft mode (linespace to 1.5)?

#### Global parameters
params:
  corrections: false # set false to stop applying blue background to blocks of corrections
  decimal_digits: 3 # set number of decimal digits to use in printing output

#### Bibliography options
bibliography: references/biblio.bib
biblatexoptions:

#### Output options
output:
  bookdown::pdf_book:
    template: templates/template.tex
    latex_engine: pdflatex
    keep_tex: true
    citation_package: biblatex
    extra_dependencies:
      hyperref: ['colorlinks = true', 'allcolors = blue', 'linktoc = true', 'bookmarksdepth = 3']
      caption: ['format = hang', 'labelfont = bf', 'textfont = bf']
      biblatex-chicago:
        - authordate
        - backend = biber
        - related = false
        - sorting = nyt
        - includeall = false
        - giveninits = true
        - uniquename = mininit
        - date = year
        - noibid
      amsmath: null
      amssymb: null
      dsfont: null
      graphicx: null
      subcaption: null
      ragged2e: null
      floatrow: null
    includes:
      before_body: 'templates/preamble.tex'
    pandoc_args: ['--top-level-division=section', '--lua-filter=bookdown/scripts_and_filters/correction_filter.lua']
  bookdown::gitbook:
    css: templates/style.css
    config:
      sharing:
        facebook: false
        twitter: yes
        all: false
  bookdown::word_document2:
    toc: true   
link-citations: true
documentclass: article

---

```{r set-global-chunk-options, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, cache = TRUE, 
  out.width = '90%', fig.pos = 'htbp!'
)
```

```{r create-chunk-options, include=FALSE, eval=knitr::is_latex_output()}
source('bookdown/scripts_and_filters/create_chunk_options.R')
source('bookdown/scripts_and_filters/wrap_lines.R')
```
<!--
Include the create_chunk_options chunk above at the top of your index.Rmd file
This will include code to create additional chunk options (e.g. for adding author references to savequotes)
and to make sure lines in code soft wrap
If you need to create your own additional chunk options, edit the file scripts/create_chunk_options.R
-->

```{r setup, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse, quietly = TRUE)
library(knitr, quietly = TRUE)
library(haven, quietly = TRUE)
library(kableExtra, quietly = TRUE)
library(labelled, quietly = TRUE)
library(RColorBrewer, quietly = TRUE)
library(srvyr, quietly = TRUE)
library(survey, quietly = TRUE)

options(knitr.kable.NA = '')
options(survey.lonely.psu = 'certainty')

# Set the theme
my_theme <- theme_light() +
  theme(panel.border = element_blank(),
        axis.line = element_line(colour = 'black'),
        panel.grid = element_line(colour = '#d9e6eb', linetype = 2), # Stata's bluishgray
        strip.text = element_text(colour = 'black'),
        legend.position = 'bottom', 
        text = element_text(size = 12))
theme_set(my_theme)  

# Set palette
palette_okabe_ito <- c('#56b4e9', '#e69f00', '#009e73', '#f0e442', '#0072b2', '#d55e00', '#cc79a7', '#000000')

scale_colour_discrete <- function(...) scale_colour_manual(..., values = palette_okabe_ito)
scale_fill_discrete <- function(...) scale_fill_manual(... , values = palette_okabe_ito)
```

```{r introduction, child = '_00-introduction.Rmd'}
```
